#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Tapping cask..."
        # Install brew cask
        brew tap homebrew/cask
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'git'
            'ack'
            'bash'
            'bash-completion'
            'ffmpeg'
            'graphicsmagick'
            'jpeg'
            'node'
            'nvm'
            'optipng'
            'tree'
            'svn'
            'wget'
            'yarn'
            'zsh'
            'zsh-completions'
            'zsh-autosuggestions'
            'gh'
            'mas'
            'postgresql'
            'grep'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        # use latest rsync rather than out-dated OS X rsync
        # install separately from the main formulae list to fix gh-19
        brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/rsync.rb

        # Install Homebrew casks
        e_header "Install cask apps..."
        brew install --cask moom
        brew install --cask 1password
        brew install --cask aerial
        brew install --cask iterm2
        brew install --cask docker
        brew install --cask visual-studio-code
        brew install --cask notion
        brew install --cask ImageOptim
        brew install --cask alfred
        brew install --cask dropbox
        brew install --cask keycastr
        brew install --cask caffeine
        brew install --cask cloudapp
        ### Quicklook plugins https://github.com/sindresorhus/quick-look-plugins
        brew install --cask qlcolorcode # syntax highlighting in preview
        brew install --cask qlstephen  # preview plaintext files without extension
        brew install --cask qlmarkdown  # preview markdown files
        brew install --cask quicklook-json  # preview json files
        brew install --cask slack
        brew install --cask zoomus
        brew install --cask signal
        brew install --cask hot
        brew install --cask bartender
        brew install --cask pika
        brew install --cask loom
        brew install --cask rescuetime
        brew install --cask clocker
        brew install --cask fantastical
        brew install --cask tweetbot
        brew install --cask kap
        brew install --cask postman
        brew install --cask rocket
        brew install --cask firefox
        brew install --cask google-chrome
        [[ $? ]] && e_success "Done"

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
