#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Tapping cask..."
        # Install brew cask
        brew tap caskroom/cask
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'coreutils' # GNU core utilities (those that come with OS X are outdated)
            'git'
            'ack'
            'bash'
            'bash-completion'
            'ffmpeg'
            'graphicsmagick'
            'jpeg'
            'node'
            'nvm'
            'optipng'
            'tree'
            'wget'
            'yarn'
            'zsh'
            'zsh-completions'
            'zsh-autosuggestions'
            'gh'
            'mas'
            'postgresql'
            'grep'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        # use latest rsync rather than out-dated OS X rsync
        # install separately from the main formulae list to fix gh-19
        brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/rsync.rb

        # Install Homebrew casks
        e_header "Install cask apps..."
        brew cask install moom
        brew cask install 1password
        brew cask install aerial
        brew cask install iterm2
        brew cask install docker
        brew cask install visual-studio-code
        brew cask install notion
        brew cask install ImageOptim
        brew cask install alfred
        brew cask install dropbox
        brew cask install keycastr
        brew cask install caffeine
        brew cask install cloudapp
        ### Quicklook plugins https://github.com/sindresorhus/quick-look-plugins
        brew cask install qlcolorcode # syntax highlighting in preview
        brew cask install qlstephen  # preview plaintext files without extension
        brew cask install qlmarkdown  # preview markdown files
        brew cask install quicklook-json  # preview json files
        brew cask install slack
        brew cask install zoomus
        brew cask install signal
        brew cask install hot
        brew cask install bartender
        brew cask install pika
        brew cask install loom
        brew cask install rescuetime
        brew cask install clocker
        brew cask install fantastical
        brew cask install tweetbot
        brew cask install kap
        brew cask install postman
        brew cask install rocket
        brew cask install firefox
        brew cask install google-chrome
        [[ $? ]] && e_success "Done"

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
