#!/bin/bash

run_fonts() {

#############################################
### Fonts
#############################################

echo "Installing fonts..."

brew tap homebrew/cask-fonts

### programming fonts
brew install font-jetbrains-mono
brew install font-jetbrains-mono-nerd-font
brew install font-fira-mono-for-powerline
brew install font-fira-code

### SourceCodePro + Powerline + Awesome Regular (for powerlevel 9k terminal icons)
cd ~/Library/Fonts && { curl -O 'https://github.com/Falkor/dotfiles/blob/master/fonts/SourceCodePro+Powerline+Awesome+Regular.ttf?raw=true' ; cd -; }
}
