#!/bin/bash

run_list() {

cat <<EOT

OS X dotfiles - Simon Taggart - http://simontaggart.com/

Additional software to install

Browsers:
    Firefox
    Google Chrome

Development:
    iTerm 2
    ImageAlpha
    Kaleidoscope
    ImageOptim
    VirtualBox
    VS Code

Other:
    Alfred
    CloudApp
    Dropbox
    Moom
    Dropbox
    Sip
    1Password
    Skype
    TweetBot
    Wallcat
EOT

}
