#!/bin/bash

run_oh_my_zsh() {

#############################################
### Install oh my zsh things
#############################################

echo "Installing oh-my-zsh..."

if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
}
